name: Build

on:
  push:
    branches: [main]
    paths:
      - "Translation/**"
  pull_request:
    branches: [main]
    paths:
      - "Translation/**"
  workflow_dispatch:

jobs:
  build:
    uses: TeamKugimiya/reusable-workflows/.github/workflows/TranslationPack-Build.yml@v1
    with:
      pack_name: ModsTranslationPack
    secrets: inherit
