name: CI | Contributors Update

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  contributor-update:
    name: Contributors Update
    runs-on: ubuntu-latest
    if: github.repository == 'TeamKugimiya/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v5

      - name: Generate Contributors Html Table
        id: html_list
        run: |
          list_html=$(cat <<-EOF
            python .github/scripts/contributors_generator.py
          EOF
          )
          {
            echo 'html_table<<EOF'
            $list_html
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Html Table
        run: |
          cat << EOF 
          ${{ steps.html_list.outputs.html_table }}
          EOF

      - name: Update Readme
        run: |
          python .github/scripts/content_replacer.py
        env:
          FILE_PATH: "README.md"
          MULTILINE_MODE: true
          START_TAG: "<!-- CONTRIBUTORS_CI_START -->"
          END_TAG: "<!-- CONTRIBUTORS_CI_END -->"
          CONTENT: "${{ steps.html_list.outputs.html_table }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: "docs(Readme): 更新貢獻者清單"
          commit-message: "docs(Readme): 更新貢獻者清單"
          sign-commits: true
          branch: docs/contributor-readme
          labels: |
            📃 文件
          add-paths: README.md
          body: |
            自動化 [GitHub Action][github-action] 工作流程！

            ------
            由 [create-pull-request][cpr] 自動產生

            [cpr]: https://github.com/peter-evans/create-pull-request
            [github-action]: https://github.com/features/actions
