name: CI | Labeler

on: 
  # issues:
  #   types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Path Labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/configs/labeler.yml"

      - name: Info Labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
