name: CI | Mods Counter

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  mods-counter:
    name: Mods Counter Update
    runs-on: ubuntu-latest
    if: |
      github.repository == 'TeamKugimiya/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v5

      - name: Count Mods
        id: mods
        run: | 
          NUMBER=$(python .github/scripts/mods_counter.py)
          echo "number=$NUMBER" >> "$GITHUB_OUTPUT"

      - name: Update Readme
        run: |
          python .github/scripts/content_replacer.py
        env:
          FILE_PATH: "README.md"
          MULTILINE_MODE: false
          START_TAG: "<!-- MODS_NUMBER_CI_START -->"
          END_TAG: "<!-- MODS_NUMBER_CI_END -->"
          CONTENT: "${{ steps.mods.outputs.number }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: "docs(Readme): 更新模組數量"
          commit-message: "docs(Readme): 更新模組數量"
          sign-commits: true
          branch: docs/mod-counter-readme
          labels: |
            📃 文件
          add-paths: README.md
          body: |
            自動化 [GitHub Action][github-action] 工作流程！

            ------
            由 [create-pull-request][cpr] 自動產生

            [cpr]: https://github.com/peter-evans/create-pull-request
            [github-action]: https://github.com/features/actions
