name: CI | Verify Commit

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

permissions:
  contents: read
  pull-requests: read

jobs:
  VerifyCommit:
    name: Verify Commit
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: Verify Commit
        uses: taskmedia/action-conventional-commits@v1.1.0
        with:
          types: "feat|fix|chore|ci|docs|refactor|mods_feat|mods_update|mods_fix|mods_improve|mods_localize|mods_remove"
