name: Reusable | Summary Generate

on:
  workflow_call:
    outputs:
      build_info:
        description: "Build Info"
        value: ${{ jobs.summary.outputs.build_info }}

jobs:
  summary:
    name: Summary Generate
    runs-on: ubuntu-latest

    outputs:
      build_info: ${{ steps.summary.outputs.build_info }}

    steps:
      - name: Checking Repository
        uses: actions/checkout@v4

      - name: Download All Artifact
        uses: actions/download-artifact@v4

      - name: Summary
        id: summary
        run: |
          {
            echo 'build_info<<EOF'
            python .github/scripts/summary_generate.py
            echo EOF
          } >> "$GITHUB_OUTPUT"
