name: Reusable | Modrinth Publish

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      matrix_version:
        required: true
        type: string
      codename:
        required: false
        type: string
      changelog:
        required: true
        type: string
      release:
        required: true
        type: boolean
    secrets:
      MODRINTH_TOKEN:
        required: true

jobs:
  value-extract:
    name: Value Extract
    runs-on: ubuntu-latest

    outputs:
      game_version: ${{ steps.value.outputs.game_version }}
      git_version: ${{ steps.value.outputs.git_version }}
      git_version_format: ${{ steps.value.outputs.git_version_format }}

    steps:
      - name: Checking Repository
        uses: actions/checkout@v4

      - name: Extract Values
        id: value
        run: |
          GAME_VERSION=$(python .github/scripts/version_extractor.py game_version)
          echo "game_version=$GAME_VERSION" >> "$GITHUB_OUTPUT"
          GIT_VERSION=git\ $(git rev-parse --short HEAD)
          echo "git_version=$GIT_VERSION" >> "$GITHUB_OUTPUT"
          GIT_VERSION_FORMAT=git-$(git rev-parse --short HEAD)
          echo "git_version_format=$GIT_VERSION_FORMAT" >> "$GITHUB_OUTPUT"
        env:
          matrix_version: ${{ inputs.matrix_version }}

  modrinth-publish:
    name: Modrinth Publish ${{ inputs.version }}
    runs-on: ubuntu-latest
    needs: [ value-extract ]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ModsTranslationPack-${{ inputs.matrix_version }}

      - name: Release publish | ${{ inputs.matrix_version }}
        uses: Kir-Antipov/mc-publish@v3.3
        if: ${{ inputs.release }}
        with:
          modrinth-id: cF5VXmkW
          modrinth-unfeature-mode: subset
          name: 模組翻譯包 ${{ inputs.matrix_version }}｜${{ inputs.version }}
          version: ${{ inputs.version }}
          version-type: release
          changelog: |
            ${{ inputs.changelog }}
          loaders: minecraft
          game-versions: ${{ needs.value-extract.outputs.game_version }}
          files: |
            ModsTranslationPack-${{ inputs.matrix_version }}.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      - name: Beta publish | ${{ inputs.matrix_version }}
        uses: Kir-Antipov/mc-publish@v3.3
        if: ${{ ! inputs.release }}
        with:
          modrinth-id: cF5VXmkW
          modrinth-featured: false
          name: 模組測試包 ${{ inputs.matrix_version }}｜${{ needs.value-extract.outputs.git_version }}
          version: ${{ needs.value-extract.outputs.git_version_format }}
          version-type: beta
          changelog: |
            ${{ inputs.changelog }}
          loaders: minecraft
          game-versions: ${{ needs.value-extract.outputs.game_version }}
          files: |
            ModsTranslationPack-${{ inputs.matrix_version }}.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
