name: Reusable | Delete Artifact

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string

jobs:
  delete-artifact:
    name: Delete Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: |
            ${{ inputs.artifact_name }}