name: Scripts Test

on:
  pull_request:
    branches:
    - "main"
    paths:
    - ".github/scripts/override_mods.sh"
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  script-test:
    name: Script Test
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'
    steps:
      - name: Checking Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Testing OverrideScript
        run: .github/scripts/override_mods.sh
