name: Verify Structure

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"
    paths:
    - "assets/**"
    - "MultiVersions/**"
  pull_request:
    branches:
    - "main"
    paths:
    - "assets/**"
    - "MultiVersions/**"

permissions:
  contents: read

jobs:
  VerifyStructure:
    name: Verify Structure (${{ matrix.name }})
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    strategy:
      matrix:
        include:
          - name: "Main Assets"
            path: "assets"
          - name: "MultiVersions (Patcher)"
            path: "MultiVersions/Patcher"
          - name: "MultiVersions (Forge 1.18)"
            path: "MultiVersions/Forge/1.18"
          - name: "MultiVersions (Fabric Global)"
            path: "MultiVersions/Fabric/global"

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Verify Structure
        run: .github/scripts/verify_structure.sh ${{ matrix.path }} "${{ matrix.name }}"
