name: Verify Folder

on:
  push:
    branches:
    - "main"
    paths:
    - "assets/**"
  pull_request:
    branches:
    - "main"
    paths:
    - "assets/**"

  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  Verify:
    name: Verify Folder
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Verify Override Script
        run: .github/scripts/verify_folder.sh
