name: Verify Structure

on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"
    paths:
      - "MultiVersions/**"
      - "!MultiVersions/README.md"
  pull_request:
    branches:
      - "main"
    paths:
      - "MultiVersions/**"
      - "!MultiVersions/README.md"

permissions:
  contents: read
  pull-requests: read

jobs:
  VerifyStructure:
    name: Verify Structure
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Structure
        run: python3 .github/scripts/verify_structure.py
